---
before_script:
  - source /etc/profile

stages:
  - build

run-dpkg-buildpackage:
  stage: build
  script:
    - make build
  only:
    - /^debian/.*$/
  artifacts:
    paths:
      - _build/*.deb
      - _build/*.ddeb
      - _build/*.buildinfo
      - _build/*.changes
      - _build/*.dsc
      - _build/*.xz
  tags: []
