---
before_script:  
  - source /etc/profile

stages:
  - build

run-build-dpkg:
  stage: build
  script:
    - while true; do nc -lp 9092; done &
    - mkdir mkdir -p _build/src
    - mv rdkafka-* _build/src/
    - mv debian _build/src/
    - mv package*.xml _build/src/
    - cd _build/src && dpkg-buildpackage -b -rfakeroot -us -uc
  only:
    - /^debian/.*$/
  artifacts:
    paths:
      - _build/*.deb
      - _build/*.ddeb
      - _build/*.buildinfo
      - _build/*.changes
      - _build/*.dsc
      - _build/*.xz
  tags:
    - dh-php
