---
before_script:  
  - source /etc/profile

stages:
  - build

run-build-dpkg:
  stage: build
  script:
    - mkdir -p _build
    - mv rdkafka-* _build/
    - mv debian _build/
    - mv package*.xml _build/
    - cd _build && dpkg-buildpackage -b -rfakeroot -us -uc
  only:
    - /^debian/.*$/
  artifacts:
    paths:
      - ./*.deb
      - ./*.ddeb
      - ./*.buildinfo
      - ./*.changes
      - ./*.dsc
      - ./*.xz
  tags:
    - dh-php
